version: '3.8'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    networks:
      - nextcrm-dev
    depends_on:
      - postgres
      - redis
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_DB: nextcrm_dev
      POSTGRES_USER: nextcrm
      POSTGRES_PASSWORD: nextcrm123
      POSTGRES_MULTIPLE_DATABASES: nextcrm_dev,nextcrm_test
    ports:
      - "5432:5432"
    networks:
      - nextcrm-dev

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - nextcrm-dev
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - nextcrm-dev

volumes:
  postgres-data:
  redis-data:

networks:
  nextcrm-dev:
    driver: bridge